### ISSUE TITLE
PlayerView isEmpty

### ISSUE THREAD

**Issue by ArifJezir** [twilio/twilio-live-interactive-video#157]
pod 'TwilioLivePlayer', '1.1.0'
pod 'AmazonIVSPlayer', '1.8.0'

I integrate the Twilio live player in the storyboard custom view.   I get a player view that is nil. 
I am using player-manager delegate and get player

<img width="816" alt="Screenshot 2022-08-05 at 4 49 10 PM" src="https://user-images.githubusercontent.com/35096139/183067023-1fb9d694-1dde-4db7-98f7-b856e889b0e7.png">

**Comment by timrozum** [comment]
Hi @ArifJezir I don't think I understand the specific problem you are having.

Can you identify the specific line of code that is having an issue and what issue it is? Thanks!

**Comment by ArifJezir** [comment]
Hi @timrozum 
 I assign the player view to my custom view without layout. so i cant' see my player view. then i set layout for custom view then i can see my player view.
 
 Thats my mistake. i fixed it. so i close this ticket.
