### ISSUE TITLE
Add text chat to the iOS app

### ISSUE THREAD

**Issue by HakanSAYAR** [twilio/twilio-live-interactive-video#75]
Hi Devs,
I have an iOS application where I use 'Twilio Video iOS SDK' and configure the [twilio-video-app-ios](https://github.com/twilio/twilio-video-app-ios). Now I want to add "interactive live streaming" to this application. It says on [Twilio Live](https://www.twilio.com/live) that you also support text-based chat, but I couldn't see anything about text-based chat in the [twilio-live-interactive-video](https://github.com/twilio/twilio-live-interactive-video/tree/main/apps/ios/LiveVideo). How can I turn on text-based chat?

**Comment by appurist** [comment]
I'm just a user of this, so this may be inaccurate, but I had interactive chat by default when I only updated the environment keys with my Twilio info, did a `serverless:deploy`, then connected as a host (created new room) and a speaker. I suspect you only connected additional users _as viewers_? They may have considerably less features.

**Comment by timrozum** [comment]
Hi, the ReactJS app and the reference backend has implemented the text chat feature that uses [Twilio Conversations](https://www.twilio.com/conversations-api). This is not yet implemented for the iOS app in this repo. 

The `create-stream` endpoint in this repo does configure a new conversation. And all the endpoints to create or join a stream have a chat grant added to the token that is returned. And so you should be able to implement chat on iOS using the conversations SDK with this token. You could look at the ReactJS code for an example of how to use the conversations SDK. There is also some [example iOS code for the conversations SDK](https://www.twilio.com/docs/conversations/ios/exploring-conversations-swift-quickstart) although it is not integrated into a video app.

**Comment by timmydoza** [comment]
Hey @HakanSAYAR - we have added chat to the iOS app, powered by [Twilio Conversations](https://www.twilio.com/conversations-api). Thanks again for the feature request, and please let us know if there's anything else!
